package pitampoudel.core.domain.validators

enum class AuthValidationError {
    VALIDATION_ERROR_MUST_NOT_BE_BLANK,
    VALIDATION_ERROR_MUST_BE_SELECTED,
    VALIDATION_ERROR_TOO_SHORT,
    VALIDATION_ERROR_INVALID_URL,
    VALIDATION_ERROR_INVALID_EMAIL,
    VALIDATION_ERROR_INVALID_PHONE_NUMBER,
    VALIDATION_ERROR_PASSWORDS_DONT_MATCH,
    VALIDATION_ERROR_MUST_NOT_BE_EMPTY

}